language: rust

sudo: false

notifications:
    email: false

branches:
    only: master

script:
    - cargo build --verbose
    - cargo test  --verbose
    - ( cd bstring_macros && cargo build --verbose )
    - ( cd bstring_macros && cargo test  --verbose )
    - ( cd bstring_macros_hack && cargo build --verbose )
    - ( cd bstring_macros_hack && cargo test  --verbose )
